config/routes.rb
Rails.application.routes.draw do
  resources :adverts
  devise_for :users
  get "/:filter" => 'adverts#idnex'
  root to: 'home#index'

end

app/models/advert.rb
class Advert < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :adverts
end

app/controllers/adverts_controller.rb
class AdvertsController < ApplicationController
  before_action :set_advert, only: [:show, :edit, :update, :destroy]

  # GET /adverts
  # GET /adverts.json
  def index
    @adverts = Advert.all
    temp = Advert.maximum(:price)
    @max = temp ? temp : 1
  end

  # GET /adverts/1
  # GET /adverts/1.json
  def show
  end

  # GET /adverts/new
  def new
    @advert = Advert.new
  end

  # GET /adverts/1/edit
  def edit
  end

  # POST /adverts
  # POST /adverts.json
  def create
    @advert = Advert.new(advert_params)

    respond_to do |format|
      if @advert.save
        format.html { redirect_to @advert, notice: 'Advert was successfully created.' }
        format.json { render :show, status: :created, location: @advert }
      else
        format.html { render :new }
        format.json { render json: @advert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adverts/1
  # PATCH/PUT /adverts/1.json
  def update
    respond_to do |format|
      if @advert.update(advert_params)
        format.html { redirect_to @advert, notice: 'Advert was successfully updated.' }
        format.json { render :show, status: :ok, location: @advert }
      else
        format.html { render :edit }
        format.json { render json: @advert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adverts/1
  # DELETE /adverts/1.json
  def destroy
    @advert.destroy
    respond_to do |format|
      format.html { redirect_to adverts_url, notice: 'Advert was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advert
      @advert = Advert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advert_params
      params.require(:advert).permit(:title, :description, :user_id, :price)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

    if params[:filter].present?
      @adverts = Advert.where('price > ?', params[:filter])
    else
      @adverts = Advert.all
    end

    temp = Advert.maximum(:price)
    @max = temp ? temp-1 : 1
  end
end

app/helpers/adverts_helper.rb
module AdvertsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/adverts/_form.html.erb
<%= form_for @advert, :html => {:class => "form-horizontal advert"} do |f| %>

    <% if @advert.errors.any? %>
        <div id="error_expl" class="panel panel-danger">
          <div class="panel-heading">
            <h3 class="panel-title"><%= pluralize(@advert.errors.count, "error") %> prohibited this advert from being
              saved:</h3>
          </div>
          <div class="panel-body">
            <ul>
              <% @advert.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :title, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_field :title, :class => 'form-control' %>
      </div>

    </div>
    <div class="form-group">
      <%= f.label :description, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_field :description, :class => 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :price, :class => 'control-label col-lg-2' %>
        <div class="col-lg-10">
          <%= f.text_field :price, :class => 'form-control' %>
        </div>

      </div>
      <%= f.hidden_field :user_id, :value => current_user.id ? current_user.id : '' %>

    </div>

    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-10">
        <%= f.submit nil, :class => 'btn btn-primary' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                    adverts_path, :class => 'btn btn-default' %>
      </div>
    </div>

<% end %>

app/views/adverts/edit.html.erb
<%- model_class = Advert -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/adverts/index.html.erb
<%- model_class = Advert -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @adverts.each do |advert| %>
      <tr>
        <td><%= link_to advert.id, advert_path(advert) %></td>
        <td><%= advert.title %></td>
        <td><%= advert.price %></td>
        <td><%= advert.description %></td>
        <td><%= advert.user ?  advert.user.email : 'No user'%></td>
        <td><%=l advert.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_advert_path(advert), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      advert_path(advert),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_advert_path,
            :class => 'btn btn-primary' %>
<hr/>
Фильтр цены:
<%= form_tag "adverts" do %>
<div class="row">
  <div class="small-10 columns">
    <div class="range-slider" data-slider data-options="display_selector: #price; start: 1; end: <%= @max %>;">
      <span class="range-slider-handle" role="slider" tabindex="0"></span>
      <span class="range-slider-active-segment"></span>
    </div>
  </div>
  <div class="small-2 columns">
    <input type="number" id="price" value="" />
  </div>
</div>
    <%= submit_tag "Go with filter" %>
<% end %>

app/views/adverts/new.html.erb
<%- model_class = Advert -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/adverts/show.html.erb
<%- model_class = Advert -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @advert.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @advert.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @advert.user_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              adverts_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_advert_path(@advert), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              advert_path(@advert),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/home/index.erb
<div class="page-header">
  <h1>Adverts</h1>
</div>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Title</th>
    <th>Price</th>
    <th>Description</th>
    <th>User</th>
    <th>Date</th>
  </tr>
  </thead>
  <tbody>
  <% @adverts.each do |advert| %>
      <tr>
        <td><%= advert.title %></td>
        <td><%= advert.price %></td>
        <td><%= advert.description %></td>
        <td><%= advert.user ?  advert.user.email : 'No user'%></td>
        <td><%=l advert.created_at %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_advert_path,
            :class => 'btn btn-primary' %>
<hr/>
Фильтр цены:
<script>
    var new_value = <%=params[:filter]%>;
    $('.range-slider').foundation('slider', 'set_value', new_value);
</script>
<%= form_tag "/", method: :get  do %>
    <div class="row">
      <div class="small-10 columns">
        <div class="range-slider" data-slider data-options="display_selector: #price; start: 1; end: <%= @max %>; value: 33;">
          <span class="range-slider-handle" role="slider" tabindex="0"></span>
          <span class="range-slider-active-segment"></span>
        </div>
      </div>
      <div class="small-2 columns">
        <input name="filter" type="number" id="price" value="" />
      </div>
    </div>
    <%= submit_tag "Go with filter" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

  <title><%= content_for?(:title) ? yield(:title) : "test missions" %></title>

  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "js/vendor/modernizr" %>
  <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
  <script src="/js/foundation.min.js"></script>

  <script src="js/vendor/jquery.js"></script>
  <script src="js/foundation/foundation.js"></script>
  <script src="js/foundation/foundation.slider.js"></script>
  <%= csrf_meta_tags %>
</head>

<body>
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><a href="#">Tets mission</a></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="has-dropdown">
        <a>User panel</a>
        <ul class="dropdown">
          <% if user_signed_in? %>
              <li>
                <%= link_to(current_user.email, edit_user_registration_path) %>
              </li>
          <% else %>
              <li>
                <%= link_to('Register', new_user_registration_path) %>
              </li>
          <% end %>
        </ul>

      </li>
    </ul>

    <ul class="left">
      <li><%= link_to ' Show Adverts', adverts_path %></li>
      <li><%= link_to 'Home', root_path %></li>
    </ul>
  </section>
</nav>
<div class="row">
  <div class="large-2 columns"></div>
  <div class="large-8 columns"><%= yield %></div>
  <div class="large-2 columns"></div>
</div>


</body>
</html>

app/views/layouts/tets_mission.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TestMissions" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">TestMissions</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>